spring.application.name=Encheres
spring.profiles.active=prod

######## INFOS DE BASE DE DONNEE ########
# url de connexion
# jdbc:sqlserver:// --> protocole d'accès (jdbc) à la BDD
# localhost --> server sur lequel est située la BDD
# databaseName=filmotheque; --> nom de la BDD
# trustServerCertificate=true; --> option qui permet de spécifier qu'on fait confiance au moteur de la BDD

# user/password de connexion
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=filmotheque;trustServerCertificate=true;
spring.datasource.username=userdb
spring.datasource.password=Pa$$w0rd
